version: '3.8'

services:
  node:
    build: .
    volumes:
      - ./src:/node/src
      - ./config:/node/config
    entrypoint: 'node /node/src/cineman.js'
    links:
      - "db"
    
  db:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./volumes/db:/data/db
