version: '3'

services:
  db:
    image: mariadb

    volumes:
      - ./docker-entrypoint-initdb.d

    environment:
      - MYSQL_ROOT_PASSWORD=password # for testing
      #- MYSQL_RANDOM_ROOT_PASSWORD=yes
      
    ports:
      - 3306:3306